[package]
name = "router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.11"
mockall = "0.11.2"
tokio = { version = "1.19.2", features = ["full"] }
usecase = {path = "../usecase"}
domain = {path="../domain"}
service = {path="../service"}
repository = {path="../repository"}
sqlx = "0.6.1"
futures-util = "0.3.21"
async-trait = "0.1.57"
